"""empty message

Revision ID: 6451daf6d6af
Revises: add_catalog_tag_to_assets
Create Date: 2025-11-14 17:53:35.512231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6451daf6d6af'
down_revision = 'add_catalog_tag_to_assets'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    is_sqlite = bind.dialect.name == 'sqlite'
    if is_sqlite:
        try:
            rows = bind.execute(sa.text("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE '_alembic_tmp_%'"))
            for (tname,) in rows.fetchall():
                op.execute(f"DROP TABLE IF EXISTS {tname}")
        except Exception:
            pass
    ix_asset_products = {idx['name'] for idx in inspector.get_indexes('asset_products')}
    ix_assets = {idx['name'] for idx in inspector.get_indexes('assets')}
    ix_vulnerabilities = {idx['name'] for idx in inspector.get_indexes('vulnerabilities')}
    cols_vulnerabilities = {col['name'] for col in inspector.get_columns('vulnerabilities')}
    uq_risk_assessment = {uc['name'] for uc in inspector.get_unique_constraints('risk_assessment')}
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_products', schema=None) as batch_op:
        try:
            if batch_op.f('ix_asset_products_asset_id') not in ix_asset_products and 'ix_asset_products_asset_id' not in ix_asset_products:
                batch_op.create_index(batch_op.f('ix_asset_products_asset_id'), ['asset_id'], unique=False)
        except Exception:
            pass
        try:
            if 'ix_asset_products_installed_version' not in ix_asset_products:
                batch_op.create_index('ix_asset_products_installed_version', ['installed_version'], unique=False)
        except Exception:
            pass
        try:
            if 'ix_asset_products_model_name' not in ix_asset_products:
                batch_op.create_index('ix_asset_products_model_name', ['model_name'], unique=False)
        except Exception:
            pass
        try:
            if 'ix_asset_products_operating_system' not in ix_asset_products:
                batch_op.create_index('ix_asset_products_operating_system', ['operating_system'], unique=False)
        except Exception:
            pass
        try:
            if batch_op.f('ix_asset_products_product_id') not in ix_asset_products and 'ix_asset_products_product_id' not in ix_asset_products:
                batch_op.create_index(batch_op.f('ix_asset_products_product_id'), ['product_id'], unique=False)
        except Exception:
            pass

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('asset_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        if batch_op.f('ix_assets_ip_address') not in ix_assets:
            batch_op.create_index(batch_op.f('ix_assets_ip_address'), ['ip_address'], unique=False)
        if batch_op.f('ix_assets_owner_id') not in ix_assets:
            batch_op.create_index(batch_op.f('ix_assets_owner_id'), ['owner_id'], unique=False)
        if batch_op.f('ix_assets_vendor_id') not in ix_assets:
            batch_op.create_index(batch_op.f('ix_assets_vendor_id'), ['vendor_id'], unique=False)

    with op.batch_alter_table('cve_parts', schema=None) as batch_op:
        try:
            batch_op.drop_index(batch_op.f('idx_cve_parts_part_a'), sqlite_where=sa.text("part = 'a'"))
        except Exception:
            pass
        try:
            batch_op.drop_index(batch_op.f('idx_cve_parts_part_h'), sqlite_where=sa.text("part = 'h'"))
        except Exception:
            pass
        try:
            batch_op.drop_index(batch_op.f('idx_cve_parts_part_o'), sqlite_where=sa.text("part = 'o'"))
        except Exception:
            pass

    with op.batch_alter_table('cve_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('cve_vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('product', schema=None) as batch_op:
        existing_uq = {uc['name'] for uc in inspector.get_unique_constraints('product')}
        if 'uq_product_vendor_name' not in existing_uq:
            batch_op.create_unique_constraint('uq_product_vendor_name', ['vendor_id', 'name'])

    op.execute("DELETE FROM risk_assessment WHERE id NOT IN (SELECT MAX(id) FROM risk_assessment GROUP BY asset_id, vulnerability_id)")
    with op.batch_alter_table('risk_assessment', schema=None) as batch_op:
        if 'uq_risk_asset_vuln' not in uq_risk_assessment:
            batch_op.create_unique_constraint('uq_risk_asset_vuln', ['asset_id', 'vulnerability_id'])

    with op.batch_alter_table('sync_metadata', schema=None) as batch_op:
        existing_ix_sync = {idx['name'] for idx in inspector.get_indexes('sync_metadata')}
        if batch_op.f('ix_sync_metadata_last_modified') in existing_ix_sync or 'ix_sync_metadata_last_modified' in existing_ix_sync:
            batch_op.drop_index(batch_op.f('ix_sync_metadata_last_modified'))

    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        if batch_op.f('ix_vulnerabilities_cvss_score') not in ix_vulnerabilities:
            batch_op.create_index(batch_op.f('ix_vulnerabilities_cvss_score'), ['cvss_score'], unique=False)
        if batch_op.f('ix_vulnerabilities_patch_available') not in ix_vulnerabilities:
            batch_op.create_index(batch_op.f('ix_vulnerabilities_patch_available'), ['patch_available'], unique=False)
        if 'risks' in cols_vulnerabilities:
            batch_op.drop_column('risks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risks', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_patch_available'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_cvss_score'))

    with op.batch_alter_table('sync_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_metadata_last_modified'), ['last_modified'], unique=False)

    with op.batch_alter_table('risk_assessment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_risk_asset_vuln', type_='unique')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_vendor_name', type_='unique')

    with op.batch_alter_table('cve_vendors', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('cve_products', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('cve_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_cve_parts_part_o'), ['cve_id'], unique=False, sqlite_where=sa.text("part = 'o'"))
        batch_op.create_index(batch_op.f('idx_cve_parts_part_h'), ['cve_id'], unique=False, sqlite_where=sa.text("part = 'h'"))
        batch_op.create_index(batch_op.f('idx_cve_parts_part_a'), ['cve_id'], unique=False, sqlite_where=sa.text("part = 'a'"))

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_assets_owner_id'))
        batch_op.drop_index(batch_op.f('ix_assets_ip_address'))
        batch_op.alter_column('asset_type',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('asset_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_products_product_id'))
        batch_op.drop_index('ix_asset_products_operating_system')
        batch_op.drop_index('ix_asset_products_model_name')
        batch_op.drop_index('ix_asset_products_installed_version')
        batch_op.drop_index(batch_op.f('ix_asset_products_asset_id'))

    # ### end Alembic commands ###
