"""rename_metadata_to_message_metadata_in_chat_messages

Revision ID: 76d22d433c70
Revises: add_chat_system_tables
Create Date: 2025-09-29 10:45:42.885770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '76d22d433c70'
down_revision = 'add_chat_system_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_metadata', sa.Text(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('metadata')

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_chat_sessions_session_token'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_chat_sessions_session_token'), ['session_token'])

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', sqlite.JSON(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('message_metadata')

    # ### end Alembic commands ###
