"""Add cve_parts table

Revision ID: 9ecf1bfada54
Revises: 29ec59dc6d2e
Create Date: 2025-10-31 11:10:42.053909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecf1bfada54'
down_revision = '29ec59dc6d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_parts',
    sa.Column('cve_id', sa.String(), nullable=False),
    sa.Column('part', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('cve_id', 'part', name='pk_cve_part')
    )
    with op.batch_alter_table('cve_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cve_parts_cve_id'), ['cve_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cve_parts_part'), ['part'], unique=False)
        batch_op.create_index('ix_cve_parts_part_cve', ['part', 'cve_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cve_parts', schema=None) as batch_op:
        batch_op.drop_index('ix_cve_parts_part_cve')
        batch_op.drop_index(batch_op.f('ix_cve_parts_part'))
        batch_op.drop_index(batch_op.f('ix_cve_parts_cve_id'))

    op.drop_table('cve_parts')
    # ### end Alembic commands ###
