"""Add created_at and updated_at to weaknesses table

Revision ID: ff55b16f37f6
Revises: 
Create Date: 2025-09-27 11:01:48.959369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff55b16f37f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)
    existing = set(insp.get_table_names())
    if 'cve_product' in existing:
        op.drop_table('cve_product')
    if 'newsletter_subscribers' in existing:
        op.drop_table('newsletter_subscribers')
    if 'cve_vendor' in existing:
        op.drop_table('cve_vendor')
    if 'weaknesses' in existing:
        with op.batch_alter_table('weaknesses', schema=None) as batch_op:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
            batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weaknesses', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.create_table('cve_vendor',
    sa.Column('cve_id', sa.TEXT(), nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cve_id'], ['vulnerabilities.cve_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('cve_id', 'vendor_id')
    )
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('subscribed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('unsubscribed_at', sa.DATETIME(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), server_default=sa.text("'website'"), nullable=True),
    sa.Column('preferences', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cve_product',
    sa.Column('cve_id', sa.TEXT(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cve_id'], ['vulnerabilities.cve_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('cve_id', 'product_id')
    )
    # ### end Alembic commands ###
